###################################################################################
#          Delete All Configured Secondary IP Addresses From Interfaces           #
###################################################################################
---
- name: Remove All Secondary IP Addresses from Interfaces
  hosts: nxos
  gather_facts: false

  vars:
    intflist: []

  tasks:
    - name: Retrieving all interfaces
      nxos_command:
        commands: show running-config | include ^interface
      register: intf_list

    - name: Retrieving secondary ip address configurations (step 1 of 2)
      nxos_command:
        commands: show running-config {{ item }} | in ^\s+ip\saddress.*secondary$
      register: intf_config
      loop: "{{ intf_list.stdout_lines[0] }}"

    - name: Retrieving secondary ip address configurations (step 2 of 2)
      set_fact:
        intflist: "{{ intflist | default([]) + [{ 'interface': item.item, 'secondaryip': item.stdout_lines[0] }] }}"
      loop: "{{ intf_config.results }}"
      when: "item.stdout[0] != ''"

    - name: Removing secondary ip address
      nxos_config:
        lines:
        - no {{ item.1 }}
        parents: "{{ item.0.interface }}"
      loop: "{{ intflist | subelements('secondaryip', 'skip_missing=True') }}"
